[project]
name = "workspaces"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "base58>=2.1.1",
    "ecdsa>=0.19.0",
    "fastapi[all]>=0.115.0",
    "pydantic>=2.9.2",
    "requests>=2.32.3",
]
